# Generated by Django 3.1.1 on 2020-10-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20201028_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktop',
            name='status',
            field=models.CharField(choices=[('RESTOCKING', 'Item restocking in few days'), ('AVAILABLE', 'Item ready to be purchased'), ('SOLD', 'Item already sold')], default='SOLD', max_length=10),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='status',
            field=models.CharField(choices=[('RESTOCKING', 'Item restocking in few days'), ('AVAILABLE', 'Item ready to be purchased'), ('SOLD', 'Item already sold')], default='SOLD', max_length=10),
        ),
        migrations.AlterField(
            model_name='phone',
            name='status',
            field=models.CharField(choices=[('RESTOCKING', 'Item restocking in few days'), ('AVAILABLE', 'Item ready to be purchased'), ('SOLD', 'Item already sold')], default='SOLD', max_length=10),
        ),
    ]
